schemaVersion: 1
sessionDefaults:
  projectPath: /Users/coffegorio/Development/Fluffy/mobile/Fluffy.xcodeproj
  scheme: Fluffy
  configuration: Debug
  simulatorName: iPhone 17 Pro
  simulatorId: E2482921-6273-4C0F-AE43-8B4D691D2F4B
  useLatestOS: true
  bundleId: fluffy.Fluffyyyyy
  simulatorPlatform: iOS Simulator
