schemaVersion: 1
sessionDefaults:
  projectPath: /Users/coffegorio/Development/Fluffy/iOS/Fluffy-SUI/Fluffy.xcodeproj
  scheme: Fluffy
  configuration: Debug
  simulatorName: iPhone 17 Pro
  simulatorId: 94C1F0EB-798C-4E2B-932D-0155B3955707
  useLatestOS: true
  bundleId: fluffy.Fluffyyyyy
  simulatorPlatform: iOS Simulator
